on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: lts/*

      - run: npm ci
      - run: npm test
      - run: npm run build

      - uses: JS-DevTools/npm-publish@main
        with:
          token: ${{secrets.NPM_ACCESS_TOKEN}}
